Upgraded needToChargeBatteries() and driveRoverToTarget()
Pesterenan/MechPeste-Java pull request #11
Opened 2022-11-03 03:41 UTC by william64644

needToChargeBatteries() is now following the clean code rules bellow:
Functions should not do more than one thing.
Functions must never do more than what they imply to do.

Clean code rules and best practices in general improve code scalability, legibility and reliability.

The process and the changes were decently documented along the commits.

2022-11-03 04:21 UTC, Pesterenan requested changes
These are the changes that I saw for now. Also there's some blank lines here and there. Also try to pull other changes to the dev branch! Thanks for the help!

2022-11-03 04:21 UTC, Pesterenan commented on src/com/pesterenan/controllers/RoverController.java
> +			haveSolarPanels = detectSolarPanels();
This shouldn't be a variable that is updated only here, we need to check this before every recharge cycle, as the rover could've lost some solar panel.

2022-11-03 04:21 UTC, Pesterenan commented on src/com/pesterenan/controllers/RoverController.java
> +	private boolean detectSolarPanels() throws RPCException {
Nice, abstracting away this function is the right thing to do. As it already returns a boolean, we can call it "hasWorkingSolarPanels" and call it whenever we start to recharge the rover.

2022-11-03 04:21 UTC, Pesterenan commented on src/com/pesterenan/controllers/RoverController.java
> +				if (haveSolarPanels) {
You can call the "hasWorkingSolarPanels" function right here.

2022-11-03 04:21 UTC, Pesterenan commented on src/com/pesterenan/controllers/RoverController.java
> +				TotalEnergyFlow += sp.getEnergyFlow();
Use camelCase when naming variables.

2022-11-03 04:21 UTC, Pesterenan commented on src/com/pesterenan/controllers/RoverController.java
> +	private boolean haveSolarPanels;
We won't need this field.

2022-11-03 04:21 UTC, Pesterenan commented on src/com/pesterenan/controllers/RoverController.java
> +				} else { // Rover arrived at destiny
This should be abstracted away as a function, but I'll take care of that later.

2022-11-03 21:36 UTC, william64644 commented on src/com/pesterenan/controllers/RoverController.java
> +			haveSolarPanels = detectSolarPanels();
haveSolarPanels don't exist anymore, instead, hasWorkingSolarPanels() is called dynamically

2022-11-03 21:37 UTC, william64644 commented on src/com/pesterenan/controllers/RoverController.java
> +	private boolean detectSolarPanels() throws RPCException {
Renaming detectSolarPanels() to hasWorkingSolarPanels() done

2022-11-03 21:38 UTC, william64644 commented on src/com/pesterenan/controllers/RoverController.java
> +				if (haveSolarPanels) {
Now hasWorkingSolarPanels() is being called here

2022-11-03 21:38 UTC, william64644 commented on src/com/pesterenan/controllers/RoverController.java
> +				TotalEnergyFlow += sp.getEnergyFlow();
Naming convention is now fixed

2022-11-03 21:40 UTC, william64644 commented on src/com/pesterenan/controllers/RoverController.java
> +	private boolean haveSolarPanels;
haveSolarPanels is not being used anymore and got deleted

2022-11-03 21:42 UTC, william64644 commented on src/com/pesterenan/controllers/RoverController.java
> +				} else { // Rover arrived at destiny
Sounds like a good choice, as I don't really know how to manipulate your GUI

2022-11-03 21:47 UTC, william64644 commented
PS: You can talk to me in Portuguese if you prefer, I'm brazilian, I just like to keep the English as a default in my workflow

2022-11-03 21:54 UTC, william64644 commented
I tried switching the base of my branch to your Dev branch but it said there was a conflict and it wasn't even clear what the problem was for me to fix it

2022-11-04 02:25 UTC, Pesterenan commented
Boa William, é nóis mano! Gostei das mudanças, vou ajustar os arquivos de configuração, assim você não vai precisar ficar trocando no fim. Depois disso, vou atualizar tanto a Dev quanto a Master, aí quando vc for subir código, pega da master, sobe uma branch, e depois a gente faz um merge na dev primeiro, blzinha?

2022-11-04 02:30 UTC, Pesterenan approved these changes

2022-11-04 02:31 UTC, merged